### ISSUE TITLE
Python error when searching

### ISSUE THREAD

**Issue by pmcmonteiro** [kartoza/SpeciesExplorer#12]
After normal installation in Qgis 3.16.16, when attempting to find a species, the result is a Python error, related to keyword argument 'encoding'.
My locale encoding is not UTF-8

![imagem](https://user-images.githubusercontent.com/101188085/168239584-4867ddf6-7e10-4714-8563-c9298e44c157.png)
             
2022-05-13T09:03:09     WARNING    Traceback (most recent call last):
              File "C:\Users/pedromonteiro/AppData/Roaming/QGIS/QGIS3\profiles\ICNF/python/plugins\SpeciesExplorer\species_explorer_dialog.py", line 70, in find
              parsed_species = name_parser(text)[0]
              File "C:\Users/pedromonteiro/AppData/Roaming/QGIS/QGIS3\profiles\ICNF/python/plugins\SpeciesExplorer\species\name_parser.py", line 20, in name_parser
              return gbif_GET(url, name, **kwargs)
              File "C:\Users/pedromonteiro/AppData/Roaming/QGIS/QGIS3\profiles\ICNF/python/plugins\SpeciesExplorer\gbifutils.py", line 39, in gbif_GET
              return json.loads(data, **encoding='utf-8'**)
              File "C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\json\__init__.py", line 359, in loads
              return cls(**kw).decode(s)
             TypeError: __init__() got an **unexpected keyword argument 'encoding'**

**Comment by Heed725** [comment]
The gbifutil.py has a line which causes that problem which causes the later qgis like yours 3.16 and even latest one 3.40 to not work 

something about being limited to python 3.9  

The good news is that you can download an older version qgis 3.8.3(Zanzibar) and be able to run the plugin smoothly without any problem 

Link for downloading older version of qgis : https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/


**Alternatively**

you could use this plugin too https://github.com/BelgianBiodiversityPlatform/qgis-gbif-api
